modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="telegram-control"
version="${version}"
displayName="Telegram Control"
logoFile="logo.png"
authors="JSaneu"
description='''
Control Minecraft from Telegram
'''
